name: CI
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: wfcd-bot-boi # env variable for username in deploy
          server-password: MAVEN_PAT # env variable for token in deploy
        env:
          MAVEN_PAT: ${{ secrets.GH_TOKEN }}
      - name: Verify
        run: mvn --batch-mode --update-snapshots verify
