name: CI
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'termurin'
      - name: Verify
        run: mvn --batch-mode --update-snapshots verify -s .mvn/settings.xml
        env:
          MAVEN_TOKEN: ${{ secrets.GH_TOKEN }}
          MAVEN_USER: ${{ secrets.GIT_AUTHOR_NAME }}
